@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "App\nClient" as appC
participant "Identity\nProvider" as idp
participant "App\nLambda" as appL
participant "**m-ld**\nGateway" as gw

activate appC
alt not logged in
	appC -> idp ++ : login
	return appToken
	alt new device
		appC -> appC : generate device key
	end
end

appC -> appL ++ : get GW token (appToken, publicKey, domainName)
appL -> appL : validate appToken
appL -> appL : check access
appL -> gw ++ : get config\n(publicKey, domainName)
note right: also ensures user is\nin domain, if required
return config
return config

appC -> gw : connect to domain (config)
deactivate appC

loop
	appC -> appC : sign operation (privateKey)
	appC --> gw : operation //via domain remotes//
	gw -> gw : validate operation (publicKey)
	gw -> gw : log operation
end

@enduml
